### ISSUE TITLE
Stable vs development version

### ISSUE THREAD

**Issue by ecodiv** [stevenpawley/r.learn.ml#3]
Hi @stevenpawley , the stable version in the grass gis addon repository does fail at the test_append test (see https://github.com/OSGeo/grass-addons/issues/495). I see that that test is not included in the development version in this repository.  Are there important differences otherwise, or could the stable version on the grass gis addon repository be updated with this development version?

**Comment by stevenpawley** [comment]
Hi Paulo, 

I haven't been working with r.learn.ml2 for a while, so I'll have to refresh my memory of what I started in the development version. I think I was playing around with turning the 'rlearnlib' modules of r.learn.ml2 into a pip-installable python package because I don't like the cumbersome method of importing modules within addons into GRASS, and also then how do you document these internal modules etc. This is because I almost always work outside of GRASS. So I was thinking of having an r.learn.ml2 python package, and I'll just push changes from the 'rlearnlib' back into the addons package which will still remain self-contained. So, you cannot install r.learn.ml2 using g.extension right now, but it is pip-installable for the core components.

I think that test_append was just the test failing rather than the append operation itself.

If you are not exclusively working within GRASS, I have been putting most new work into https://pyspatialml.readthedocs.io/en/latest/ which works well with the geopandas+rasterio type of workflow, which I'm generally using nowadays.

**Comment by ecodiv** [comment]
Hi Steven, thanks for the reply. I had a look already to your pyspatialml. Nice work, allows for a workflow I am more used to using R. Nonetheless, I hope that r.learn.ml2 will remain available as it certainly provides important functionality to the GRASS ecosystem.  Because it fails at the test_append test, it is not being updated. In  OSGeo/grass-addons#495 Markus Neteler mentioned that it might be easy to fix. I had a look but it is something beyond what I can do, so I was hoping you could have a look.

**Comment by stevenpawley** [comment]
Hi Paulo,

Thanks, I've been meaning to get back to that issue and r.learn.ml2 has been lacking some TLC for a while just due to workload at the moment. GRASS obviously has lots of other advantages, especially if your datasets are not neatly aligned and you want just 'drop in' to existing datasets for new analysis, versus the clean/aligned/self-contained approach that R/Python typically dictates. Will try to fix that later this week.
